tag = "2023-08-03_v1"
use_wandb = true

[transformer]
num_layers = 6
residual_stream_size = 512
num_attention_heads = 8
context_window = 1024

[training]
batch_size = 32
learning_rate = 1e-4
device = "cuda"
dtype = "float32"

[checkpoint.schedule]
every_n_steps = 500

[eval]
split = 0.001
batch_size = 32

[eval.schedule]
every_n_steps = 500
