name: docker

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - 'poetry.lock'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/yoshimidi:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/yoshimidi:${{ github.sha }}
